# Generated by Django 4.1.5 on 2023-01-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(related_name='users', to='api.item'),
        ),
    ]
